import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-commercial-insurance-contingent-commission-audit",
  "engine": "recovery",
  "title": "Commercial Insurance Contingent Commission Audit",
  "shortTitle": "Commercial Insurance Contingent Commission Audit",
  "tagline": "Calculate contingent commissions from production, retention, and loss performance and recover missed carrier payments.",
  "industry": "Insurance Distribution Finance",
  "buyer": "Insurance agencies, brokers, and carriers",
  "uiPort": 4661,
  "apiPort": 5661,
  "accent": "#4f46e5",
  "currency": "USD",
  "primaryOutcome": "Commercial Insurance Contingent Commission Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect producer agreements, policies, written premium, earned premium, retention, loss ratios, growth measures, commission statements, and payments in one accountable workflow. Calculate contingent commissions from production, retention, and loss performance and recover missed carrier payments.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Commercial Insurance Contingent Commission Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("producer-agreement-library","CIC01","Producer agreement library","Execute producer agreement library using producer agreements, policies, written premium, earned premium, retention, loss ratios, growth measures, commission statements, and payments.","Produce a governed producer agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Producer Agreement","text","Carrier / Producer Agreement · Standard Case"],["caseReference","Producer agreement library Reference","text","CIC01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",755000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",913550],["domainDriver","Incentive Basis","select","Growth",["Growth","Retention","Profitability"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer agreement library case","Policy premium ingestion case","Written premium calculation case","Earned premium calculation case","Growth target validation case"]}),
feature("policy-premium-ingestion","CIC02","Policy premium ingestion","Execute policy premium ingestion using producer agreements, policies, written premium, earned premium, retention, loss ratios, growth measures, commission statements, and payments.","Produce a governed policy premium ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Producer Agreement","text","Carrier / Producer Agreement · Standard Case"],["caseReference","Policy premium ingestion Reference","text","CIC02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",755000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",913550],["domainDriver","Incentive Basis","select","Growth",["Growth","Retention","Profitability"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer agreement library case","Policy premium ingestion case","Written premium calculation case","Earned premium calculation case","Growth target validation case"]}),
feature("written-premium-calculation","CIC03","Written premium calculation","Execute written premium calculation using producer agreements, policies, written premium, earned premium, retention, loss ratios, growth measures, commission statements, and payments.","Produce a governed written premium calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Producer Agreement","text","Carrier / Producer Agreement · Standard Case"],["caseReference","Written premium calculation Reference","text","CIC03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",755000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",913550],["domainDriver","Incentive Basis","select","Growth",["Growth","Retention","Profitability"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer agreement library case","Policy premium ingestion case","Written premium calculation case","Earned premium calculation case","Growth target validation case"]}),
feature("earned-premium-calculation","CIC04","Earned premium calculation","Execute earned premium calculation using producer agreements, policies, written premium, earned premium, retention, loss ratios, growth measures, commission statements, and payments.","Produce a governed earned premium calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Producer Agreement","text","Carrier / Producer Agreement · Standard Case"],["caseReference","Earned premium calculation Reference","text","CIC04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",755000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",913550],["domainDriver","Incentive Basis","select","Growth",["Growth","Retention","Profitability"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer agreement library case","Policy premium ingestion case","Written premium calculation case","Earned premium calculation case","Growth target validation case"]}),
feature("growth-target-validation","CIC05","Growth target validation","Execute growth target validation using producer agreements, policies, written premium, earned premium, retention, loss ratios, growth measures, commission statements, and payments.","Produce a governed growth target validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Producer Agreement","text","Carrier / Producer Agreement · Standard Case"],["caseReference","Growth target validation Reference","text","CIC05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",755000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",913550],["domainDriver","Incentive Basis","select","Growth",["Growth","Retention","Profitability"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer agreement library case","Policy premium ingestion case","Written premium calculation case","Earned premium calculation case","Growth target validation case"]}),
feature("retention-ratio-calculation","CIC06","Retention ratio calculation","Execute retention ratio calculation using producer agreements, policies, written premium, earned premium, retention, loss ratios, growth measures, commission statements, and payments.","Produce a governed retention ratio calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Producer Agreement","text","Carrier / Producer Agreement · Standard Case"],["caseReference","Retention ratio calculation Reference","text","CIC06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",755000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",913550],["domainDriver","Incentive Basis","select","Growth",["Growth","Retention","Profitability"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer agreement library case","Policy premium ingestion case","Written premium calculation case","Earned premium calculation case","Growth target validation case"]}),
feature("loss-ratio-calculation","CIC07","Loss ratio calculation","Execute loss ratio calculation using producer agreements, policies, written premium, earned premium, retention, loss ratios, growth measures, commission statements, and payments.","Produce a governed loss ratio calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Producer Agreement","text","Carrier / Producer Agreement · Standard Case"],["caseReference","Loss ratio calculation Reference","text","CIC07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",755000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",913550],["domainDriver","Incentive Basis","select","Growth",["Growth","Retention","Profitability"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer agreement library case","Policy premium ingestion case","Written premium calculation case","Earned premium calculation case","Growth target validation case"]}),
feature("profitability-corridor","CIC08","Profitability corridor","Execute profitability corridor using producer agreements, policies, written premium, earned premium, retention, loss ratios, growth measures, commission statements, and payments.","Produce a governed profitability corridor decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Producer Agreement","text","Carrier / Producer Agreement · Standard Case"],["caseReference","Profitability corridor Reference","text","CIC08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",755000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",913550],["domainDriver","Incentive Basis","select","Growth",["Growth","Retention","Profitability"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer agreement library case","Policy premium ingestion case","Written premium calculation case","Earned premium calculation case","Growth target validation case"]}),
feature("tier-and-hurdle-calculation","CIC09","Tier and hurdle calculation","Execute tier and hurdle calculation using producer agreements, policies, written premium, earned premium, retention, loss ratios, growth measures, commission statements, and payments.","Produce a governed tier and hurdle calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Producer Agreement","text","Carrier / Producer Agreement · Standard Case"],["caseReference","Tier and hurdle calculation Reference","text","CIC09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",755000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",913550],["domainDriver","Incentive Basis","select","Growth",["Growth","Retention","Profitability"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer agreement library case","Policy premium ingestion case","Written premium calculation case","Earned premium calculation case","Growth target validation case"]}),
feature("acquisition-exclusion-control","CIC10","Acquisition exclusion control","Execute acquisition exclusion control using producer agreements, policies, written premium, earned premium, retention, loss ratios, growth measures, commission statements, and payments.","Produce a governed acquisition exclusion control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Producer Agreement","text","Carrier / Producer Agreement · Standard Case"],["caseReference","Acquisition exclusion control Reference","text","CIC10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",755000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",913550],["domainDriver","Incentive Basis","select","Growth",["Growth","Retention","Profitability"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer agreement library case","Policy premium ingestion case","Written premium calculation case","Earned premium calculation case","Growth target validation case"]}),
feature("commission-statement-audit","CIC11","Commission statement audit","Execute commission statement audit using producer agreements, policies, written premium, earned premium, retention, loss ratios, growth measures, commission statements, and payments.","Produce a governed commission statement audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Producer Agreement","text","Carrier / Producer Agreement · Standard Case"],["caseReference","Commission statement audit Reference","text","CIC11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",755000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",913550],["domainDriver","Incentive Basis","select","Growth",["Growth","Retention","Profitability"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer agreement library case","Policy premium ingestion case","Written premium calculation case","Earned premium calculation case","Growth target validation case"]}),
feature("carrier-claim-package","CIC12","Carrier claim package","Execute carrier claim package using producer agreements, policies, written premium, earned premium, retention, loss ratios, growth measures, commission statements, and payments.","Produce a governed carrier claim package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Producer Agreement","text","Carrier / Producer Agreement · Standard Case"],["caseReference","Carrier claim package Reference","text","CIC12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",755000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",913550],["domainDriver","Incentive Basis","select","Growth",["Growth","Retention","Profitability"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer agreement library case","Policy premium ingestion case","Written premium calculation case","Earned premium calculation case","Growth target validation case"]}),
feature("payment-reconciliation","CIC13","Payment reconciliation","Execute payment reconciliation using producer agreements, policies, written premium, earned premium, retention, loss ratios, growth measures, commission statements, and payments.","Produce a governed payment reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Producer Agreement","text","Carrier / Producer Agreement · Standard Case"],["caseReference","Payment reconciliation Reference","text","CIC13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",755000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",913550],["domainDriver","Incentive Basis","select","Growth",["Growth","Retention","Profitability"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer agreement library case","Policy premium ingestion case","Written premium calculation case","Earned premium calculation case","Growth target validation case"]}),
feature("producer-allocation","CIC14","Producer allocation","Execute producer allocation using producer agreements, policies, written premium, earned premium, retention, loss ratios, growth measures, commission statements, and payments.","Produce a governed producer allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Producer Agreement","text","Carrier / Producer Agreement · Standard Case"],["caseReference","Producer allocation Reference","text","CIC14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",755000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",913550],["domainDriver","Incentive Basis","select","Growth",["Growth","Retention","Profitability"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer agreement library case","Policy premium ingestion case","Written premium calculation case","Earned premium calculation case","Growth target validation case"]}),
feature("carrier-segment-analytics","CIC15","Carrier segment analytics","Execute carrier segment analytics using producer agreements, policies, written premium, earned premium, retention, loss ratios, growth measures, commission statements, and payments.","Produce a governed carrier segment analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Producer Agreement","text","Carrier / Producer Agreement · Standard Case"],["caseReference","Carrier segment analytics Reference","text","CIC15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",755000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",913550],["domainDriver","Incentive Basis","select","Growth",["Growth","Retention","Profitability"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer agreement library case","Policy premium ingestion case","Written premium calculation case","Earned premium calculation case","Growth target validation case"]})
]);
